version: "3.0"

services:
  pdf-backend:
    build: .
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0